services:
  - type: web
    name: backend
    env: go
    plan: free
    region: oregon
    buildCommand: go build -o app ./main.go
    startCommand: ./app
    envVars:
      - key: PORT
        value: 8080 # Default port for Render web services
        sync: false
      - key: FIREBASE_AUTH_CERT_URL
        sync: false
      - key: FIREBASE_CLIENT_CERT_URL
        sync: false
      - key: FIREBASE_UNIVERSE_DOMAIN
        sync: false
